spring:
    application:
        name: AthletiCore
        holiday-api:
            url: "https://date.nager.at/api/v3/PublicHolidays/%s/%s"
            region: "UA"
            date-format: "yyyy-MM-dd"
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
    sql:
      init:
        schema-locations: classpath:/schema.sql
        data-locations: classpath:/data.sql
    security:
      jwtToken: "8H8L8WT9gIYOW/9dlDIYLuPvsHMTOAoV2cywT8VWX4MsGuGVm5S5+YDWHFv/XyjP"



springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
