CREATE TABLE notifications
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE    VARCHAR(255),
    SESSION_ID BIGINT,
    CONSTRAINT fk_session
        FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS (ID)
);