CREATE TABLE notification_clients
(
    NOTIFICATION_ID BIGINT NOT NULL,
    CLIENT_ID       BIGINT NOT NULL,
    PRIMARY KEY (NOTIFICATION_ID, CLIENT_ID),
    CONSTRAINT fk_notification
        FOREIGN KEY (NOTIFICATION_ID) REFERENCES NOTIFICATIONS (ID)
            ON DELETE CASCADE,
    CONSTRAINT fk_client
        FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID)
            ON DELETE CASCADE
);